name: Run code checks

on: [push, pull_request]

jobs:
  build:
    name: Run all checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: Compile
        run: make build
      - name: Compile test binary
        run: TEST=./stackpath make test-compile
      - name: Check fmt
        run: make fmtcheck
      - name: Vet
        run: make vet
